# I. CÂU HỎI TỰ LUẬN

---

## 1. Viết class và cài phương thức Softmax

Xây dựng lớp `Softmax` và `softmax_stable` nhận đầu vào là mảng 1 chiều (tensor 1 chiều) dựa vào kế thừa từ lớp `torch.nn.Module`

<div style="border-bottom: 1px dashed white;"></div>

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Softmax(nn.Module):
    def __init__(self):
        super(Softmax, self).__init__()
    
    def forward(self, x):
        return F.softmax(x, dim=-1)

class softmax_stable(nn.Module):
    def __init__(self):
        super(softmax_stable, self).__init__()
    
    def forward(self, x):
        max_val = torch.max(x)
        exp_x = torch.exp(x - max_val)
        sum_exp_x = torch.sum(exp_x)
        return exp_x / sum_exp_x

In [10]:
data = torch.Tensor ([1, 2, 3])
softmax = Softmax()
output = softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [11]:
data = torch.Tensor ([1, 2, 3])
softmax_stable = softmax_stable()
output = softmax_stable(data)
output

tensor([0.0900, 0.2447, 0.6652])

---

## 2. Tạo một lớp Ward với danh sách các đối tượng Person

Một Ward (phường) gồm có : name (string) và list chứa mọi người trong Ward.

Một người person có thể là student, doctor, hoặc teacher :

- Một student gồm có : name, yob (int) (năm sinh) và grade (string);
- Một teacher gồm có : name, yob và subject (string);
- Một doctor gồm có : name, yob và specialist (string).

<div style="border-bottom: 1px dashed white;"></div>

**Task a :** Tạo class Student, Doctor và Teacher (dùng `describe()` method để in tất cả thông tin của các object)

In [12]:
class Student():
    def __init__(self, name, yob, grade):
        self.name = name
        self.yob = yob
        self.grade = grade
    
    def describe(self):
        return f'Student - Name: {self.name} - Yob: {self.yob} - Grade: {self.grade}'

student1 = Student('studentA', 2010, '7')
student1.describe()

'Student - Name: studentA - Yob: 2010 - Grade: 7'

In [16]:
class Teacher():
    def __init__(self, name, yob, subject):
        self.name = name
        self.yob = yob
        self.subject = subject
    
    def describe(self):
        return f'Teacher - Name: {self.name} - Yob: {self.yob} - Subject: {self.subject}'

teacher1 = Teacher('teacherA', 1969, 'Math')
teacher1.describe()

'Teacher - Name: teacherA - Yob: 1969 - Subject: Math'

In [17]:
class Doctor():
    def __init__(self, name, yob, specialist):
        self.name = name
        self.yob = yob
        self.specialist = specialist
    
    def describe(self):
        return f'Doctor - Name: {self.name} - Yob: {self.yob} - Specialist: {self.specialist}'

doctor1 = Doctor('doctorA', 1945, 'Endocrinologists')
doctor1.describe()

'Doctor - Name: doctorA - Yob: 1945 - Specialist: Endocrinologists'

**Task b :**

Tạo class Ward và viết `add_person(person)` method để add thêm một người mới vào danh sách người của Ward.

Tạo ra một Ward object và thêm vào 1 student, 2 teacher và 2 doctor và viết `describe()` method để in ra tên Ward cũng như tất cả thông tin của từng người trong Ward

In [21]:
class Ward:
    def __init__(self, name):
        self.name = name
        self.people = []

    def add_person(self, person):
        self.people.append(person)
        
    def describe(self):
        description = f'Ward : {self.name} \n'
        for person in self.people:
            description += person.describe() + '\n'
        return description

In [ ]:
teacher2 = Teacher('teacherB', 1995, 'History')
doctor2 = Doctor('doctorB', 1975, 'Cardiologists')

In [23]:
ward1 = Ward('Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

print(ward1.describe())

Ward : Ward1 
Student - Name: studentA - Yob: 2010 - Grade: 7
Teacher - Name: teacherA - Yob: 1969 - Subject: Math
Teacher - Name: teacherB - Yob: 1995 - Subject: History
Doctor - Name: doctorA - Yob: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - Yob: 1975 - Specialist: Cardiologists



**Task c :** Viết `count_doctor()` method để đếm số lượng doctor trong Ward

In [25]:
class Ward:
    def __init__(self, name):
        self.name = name
        self.people = []

    def add_person(self, person):
        self.people.append(person)
    
    def count_doctor(self):
        return sum(1 for person in self.people if isinstance(person, Doctor))

In [26]:
ward1 = Ward('Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

ward1.count_doctor()

2

**Task d :** Viết `sord_age()` method để sắp xếp mọi người trong Ward theo tuổi của họ với thứ tự tăng dần

In [31]:
class Ward:
    def __init__(self, name):
        self.name = name
        self.people = []

    def add_person(self, person):
        self.people.append(person)
    
    def sort_age(self):
        self.people.sort(key=lambda person: person.yob, reverse=True)
    
    def describe(self):
        description = f'Ward : {self.name} \n'
        for person in self.people:
            description += person.describe() + '\n'
        return description

In [32]:
ward1 = Ward('Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

ward1.sort_age()
print(ward1.describe())

Ward : Ward1 
Student - Name: studentA - Yob: 2010 - Grade: 7
Teacher - Name: teacherB - Yob: 1995 - Subject: History
Doctor - Name: doctorB - Yob: 1975 - Specialist: Cardiologists
Teacher - Name: teacherA - Yob: 1969 - Subject: Math
Doctor - Name: doctorA - Yob: 1945 - Specialist: Endocrinologists



**Task e :** Viết `compute_average()` method để tính trung bình năm sinh của các teacher trong Ward

In [33]:
class Ward:
    def __init__(self, name):
        self.name = name
        self.people = []

    def add_person(self, person):
        self.people.append(person)
    
    def compute_average(self):
        teachers = [person.yob for person in self.people if isinstance(person, Teacher)]
        if not teachers:
            return 0
        return sum(teachers) / len(teachers)

In [35]:
ward1 = Ward('Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

print(f'Average year of birth (teacher) : {ward1.compute_average()}')

Average year of birth (teacher) : 1982.0


---

## 3. Xây dựng Class Stack

Sử dụng các phương thức :
- initialization
- is_empty
- is_full
- push(value)
- pop
- top

<div style="border-bottom: 1px dashed white;"></div>

In [47]:
class MyStack:
    def __init__(self, capacity):
        self.stack = []
        self.capacity = capacity

    def is_empty(self):
        return len(self.stack) == 0

    def is_full(self):
        return len(self.stack) == self.capacity
    
    def push(self, value):
        if self.is_full():
            raise OverflowError('Push to a full stack')
        self.stack.append(value)

    def pop(self):
        if self.is_empty():
            raise IndexError('Pop from an empty stack')
        return self.stack.pop(-1)
    
    def top(self):
        if self.is_empty():
            raise IndexError('Top from an empty stack')
        return self.stack[-1]

In [48]:
stack1 = MyStack(5)
stack1.is_empty()

True

In [49]:
stack1.push(1)
stack1.push(2)
stack1.push(3)
stack1.push(4)
stack1.push(5)
stack1.push(6)

OverflowError: Push to a full stack

In [50]:
print(stack1.is_full())
print(stack1.top())

True
5


In [51]:
stack1.pop()
stack1.pop()
stack1.pop()
stack1.pop()
stack1.pop()
stack1.pop()

IndexError: Pop from an empty stack

In [52]:
print(stack1.is_empty())
print(stack1.top())

True


IndexError: Top from an empty stack

---

## 4. Xây dựng Class Queue

Sử dụng các phương thức :
- initialization
- is_empty
- is_full
- enqueue(value)
- dequeue
- front

<div style="border-bottom: 1px dashed white;"></div>

In [53]:
class MyQueue:
    def __init__(self, capacity):
        self.queue = []
        self.capacity = capacity

    def is_empty(self):
        return len(self.queue) == 0

    def is_full(self):
        return len(self.queue) == self.capacity

    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("Enqueue to a full queue")
        self.queue.append(value)

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Dequeue from an empty queue")
        return self.queue.pop(0)

    def front(self):
        if self.is_empty():
            raise IndexError("Front from an empty queue")
        return self.queue[0]

In [56]:
queue1 = MyQueue(5)
queue1.is_empty()

True

In [57]:
queue1.enqueue(1)
queue1.enqueue(2)
queue1.enqueue(3)
queue1.enqueue(4)
queue1.enqueue(5)
queue1.enqueue(6)

OverflowError: Enqueue to a full queue

In [58]:
print(queue1.is_full())
print(queue1.front())

True
1


In [59]:
queue1.dequeue()
queue1.dequeue()
queue1.dequeue()
queue1.dequeue()
queue1.dequeue()
queue1.dequeue()

IndexError: Dequeue from an empty queue

In [60]:
print(queue1.is_empty())
print(queue1.front())

True


IndexError: Front from an empty queue

---

# II. CÂU HỎI TRẮC NGHIỆM

---

## Câu 1:

In [61]:
import torch
import torch.nn as nn

data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim =0)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

## Câu 2:

In [70]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        exp_x = torch.exp(x)
        sum_exp_x = torch.sum(exp_x, dim=-1, keepdim=True)
        return exp_x / sum_exp_x

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

## Câu 3:

In [67]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_exp = torch.exp(x)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

data = torch.Tensor([1, 2, 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[0].item(), 2) == 0.0
output

tensor([0., 0., nan])

## Câu 4:

In [71]:
import torch
import torch.nn as nn

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

## Câu 5:

In [4]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob
    
    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name:str, yob:int, grade:str):
        self._name = name
        self._yob = yob
        self._grade = grade

    def describe(self):
        return f'Student - Name: {self._name} - Yob: {self._yob} - Grade: {self._grade}'

student1 = Student(name='studentZ2023', yob=2011, grade='6')
assert student1._yob == 2011
student1.describe()


'Student - Name: studentZ2023 - Yob: 2011 - Grade: 6'

## Câu 6:

In [6]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob
    
    @abstractmethod
    def describe(self):
        pass

class Teacher(Person):
    def __init__(self, name:str, yob:int, subject:str):
        self._name = name
        self._yob = yob
        self._subject = subject

    def describe(self):
        return f'Teacher - Name: {self._name} - Yob: {self._yob} - Subject: {self._subject}'

teacher1 = Teacher(name='teacherZ2023', yob=1991, subject='History')
assert teacher1._yob == 1991
teacher1.describe()

'Teacher - Name: teacherZ2023 - Yob: 1991 - Subject: History'

## Câu 7:

In [8]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob
    
    @abstractmethod
    def describe(self):
        pass

class Doctor(Person):
    def __init__(self, name:str, yob:int, specialist:str):
        self._name = name
        self._yob = yob
        self._specialist = specialist

    def describe(self):
        return f'Doctor - Name: {self._name} - Yob: {self._yob} - Subject: {self._specialist}'

doctor1 = Doctor(name='doctorZ2023', yob=1981, specialist='Endocrinologists')
assert doctor1._yob == 1981
doctor1.describe()

'Doctor - Name: doctorZ2023 - Yob: 1981 - Subject: Endocrinologists'

## Câu 8:

In [15]:
class Ward:
    def __init__(self, name:str):
        self.__name = name
        self.__listPeople = []

    def add_person(self, person:Person):
        self.__listPeople.append(person)
    
    def describe(self):
        print(f'Ward Name: {self.__name}')
        for p in self.__listPeople:
            p.describe()

    def count_doctor(self):
        return sum(1 for person in self.__listPeople if isinstance(person, Doctor))

student1 = Student(name='studentA', yob=2010, grade='7')
teacher1 = Teacher(name='teacherA', yob=1969, subject="Math")
teacher2 = Teacher(name='teacherB', yob=1995, subject="History")
doctor1 = Doctor(name='doctorA', yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name='doctorB', yob=1975, specialist="Cardiologists")
ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.count_doctor()

2

## Câu 9:

In [18]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value):
        if self.is_full():
            raise OverflowError('Push to a full stack')
        self.__stack.append(value)

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())

False


## Câu 10:

In [19]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value):
        if self.is_full():
            raise OverflowError('Push to a full stack')
        self.__stack.append(value)

    def is_empty(self):
        return len(self.__stack) == 0

    def pop(self):
        if self.is_empty():
            raise IndexError('Pop from an empty stack')
        return self.__stack.pop(-1)
    
    def top(self):
        if self.is_empty():
            raise IndexError('Top from an empty stack')
        return self.__stack[-1]

stack1 = MyStack(capacity =5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())

2


## Câu 11:

In [21]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("Enqueue to a full queue")
        self.__queue.append(value)

queue1 = MyQueue(capacity =5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())

False


## Câu 12:

In [23]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        if self.is_full():
            raise OverflowError("Enqueue to a full queue")
        self.__queue.append(value)

    def is_empty(self):
        return len(self.__queue) == 0

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Dequeue from an empty queue")
        return self.__queue.pop(0)

    def front(self):
        if self.is_empty():
            raise IndexError("Front from an empty queue")
        return self.__queue[0]

queue1 = MyQueue(capacity =5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.front())

1


[EXERCISE MODULE 1- [Week 3 - 15/06/2024]](https://docs.google.com/forms/d/e/1FAIpQLSc8yq5vcW9Dlj3ycJrTpNZF1khKvsLVTu_xNAre28Ol7lzjRw/viewscore?viewscore=AE0zAgDqlmYwJ_J80QRspcUsxhqkPWt27HZ3uMHMNwm8rFVlMKJGx3KacUlJBs71tw)